### ISSUE TITLE
Not Working with new unity Version 2021.2.3f1

### ISSUE THREAD

**Issue by Dalilon** [hwaet/UnityProjectCloner#12]
Trying to open the clone Project with the new unity Version 2021.2.3f1 doesnt work. (Windows 10)
Tryed everything -> old version works, upgraded project to new version not.

Error:
Obtained 14 stack frames
0x00007ff6c0af2381 (Unity) OnDemandScheduler::SetStandbyWorkerCount
0x00007ff6c0ab9f9a (Unity) RefreshSettings
0x00007ff6c0ad1e8f (Unity) <lambda_283f97c31f4e30d8552a28501eddf336>::operator()
0x00007ff6c0b0be41 (Unity) LMDB_Transaction::Run
0x00007ff6c0b0c1e4 (Unity) SourceAssetDBWriteTxn::Run
0x00007ff6c0ae0d5f (Unity) SourceAssetScanner::Refresh
0x00007ff6c0ab725c (Unity) RefreshInternalV2
0x00007ff6c0ac2871 (Unity) StopAssetImportingV2Internal
0x00007ff6c0aad83d (Unity) InitialRefreshV2
0x00007ff6c0308f20 (Unity) Application::InitializeProject
0x00007ff6c0751fd8 (Unity) WinMain
0x00007ff6c1a613a2 (Unity) __scrt_common_main_seh
0x00007fff5f467034 (KERNEL32) BaseThreadInitThunk
0x00007fff5fbe2651 (ntdll) RtlUserThreadStart

i have absolutly no clue why.

**Comment by ElwoodHogan** [comment]
im getting this error as well

**Comment by arkms** [comment]
If you have that problem, in ProjectCloner.cs, try to comment the line 479.
process.StartInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;

**Comment by MoxorTheOne** [comment]
> 

Hi, with this workaround now I have an error message saying "It looks like another Unity instance is running with this project open.
Multiple Unity instances cannot open the same project."

**Comment by arkms** [comment]
Just after change that lines, restart the computer and should works fine.

(Restart the computer to be sure of restart everything from Unity)

**Comment by hwaet** [comment]
Thank you arkms!
