### ISSUE TITLE
Multiple clones ?

### ISSUE THREAD

**Issue by olivbau** [hwaet/UnityProjectCloner#4]
This tool is very useful, however is there a way to have more than 1 clone ?
I'd like to have 3 instance of my editor for example

**Comment by 314pies** [comment]
Looking for this feature as well!

**Comment by 314pies** [comment]
@olivbau 
Just add this feature to my fork.
Maybe you will be interesting in testing out?
[Link](https://github.com/hwaet/UnityProjectCloner/pull/6)

**Comment by hwaet** [comment]
Thank you for contributing a solution to this! <3
