### ISSUE TITLE
Scriptable objects not being synced

### ISSUE THREAD

**Issue by nopogo** [hwaet/UnityProjectCloner#5]
Wonderful helpful tool!

a bug I found is when Updating a field in a scriptable object that lives under Assets/Resources/.... the cloned project keeps the initial values, even after opening up a "fresh" clone.

**Comment by 314pies** [comment]
Have you try “File -> Save Project“ in the origin project?

Changes with scriptable object often won’t be saved to disk until manually doing it or quitting the editor.

**Comment by occultsoftworks** [comment]
I tried that fix, doesn't seem to work. Similarly, it doesn't work if you close and re-open the editor.

**Comment by hwaet** [comment]
This may be related to a change unity added at some point: they are now checking for sim links within a project. There's a setting toggle for directory monitoring in the preferences which might be helpful. But 314pies' solution works as on 2020.3 LTS. Even saving just the scene file will update the clone and vice versa. I'll add a note to the readme to remind users to save when modifying scriptable objects in a live test scene.
